import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Coffee, LogIn, LogOut, MapPin, Play, QrCode, ScanFace, Loader2, Globe, PenLine } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useApp } from "@/lib/app-context";
import { errMsg, fetchDaySummary, fetchEmployees, fmtMinutes, fmtTime, todayIn } from "@/lib/attendance";
import { useAttendanceRealtime } from "@/hooks/use-attendance-realtime";
import { PageHeader, Panel, StatusBadge } from "@/components/att/ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route = createFileRoute("/_authenticated/attendance/check-in")({
  head: () => ({ meta: [{ title: "Check In / Out — Attendance Vala" }, { name: "description", content: "Record check-in, breaks and check-out." }] }),
  component: CheckInPage,
});

type Method = "WEB" | "GPS";
type Gps = { lat: number; lng: number; acc: number } | "unavailable" | null;

function CheckInPage() {
  const app = useApp();
  useAttendanceRealtime();
  const qc = useQueryClient();
  const today = todayIn(app.tz);
  const emps = useQuery({ queryKey: ["att", "emps"], queryFn: fetchEmployees });
  const sum = useQuery({ queryKey: ["att", "day", today], queryFn: () => fetchDaySummary(today) });
  const locs = useQuery({
    queryKey: ["att", "locations"],
    queryFn: async () => (await supabase.from("attendance_locations").select("*").eq("status", "ACTIVE").order("name")).data ?? [],
  });

  const selectable = useMemo(
    () => (emps.data ?? []).filter((e) => e.status === "ACTIVE" && (app.can.operate || e.id === app.myEmployeeId)),
    [emps.data, app],
  );
  const [empId, setEmpId] = useState<string>(app.myEmployeeId ?? "");
  const [method, setMethod] = useState<Method>("WEB");
  const [locId, setLocId] = useState<string>("");
  const [gps, setGps] = useState<Gps>(null);
  const [busy, setBusy] = useState<string | null>(null);

  const emp = selectable.find((e) => e.id === empId);
  const s = sum.data?.find((x) => x.employee_id === empId);

  function getGps() {
    if (!("geolocation" in navigator)) { setGps("unavailable"); return; }
    setBusy("gps");
    navigator.geolocation.getCurrentPosition(
      (p) => { setGps({ lat: p.coords.latitude, lng: p.coords.longitude, acc: p.coords.accuracy }); setBusy(null); },
      () => { setGps("unavailable"); setBusy(null); },
      { enableHighAccuracy: true, timeout: 15000 },
    );
  }

  async function punch(type: "CHECK_IN" | "BREAK_START" | "BREAK_END" | "CHECK_OUT") {
    if (!empId) return;
    if (method === "GPS" && (gps === null || gps === "unavailable")) { toast.error("LOCATION NOT AVAILABLE"); return; }
    setBusy(type);
    const g = method === "GPS" && gps && gps !== "unavailable" ? gps : null;
    const args: { _employee_id: string; _event_type: string; _source: string; _lat?: number; _lng?: number; _accuracy?: number; _location_id?: string } =
      { _employee_id: empId, _event_type: type, _source: method };
    if (g) { args._lat = g.lat; args._lng = g.lng; args._accuracy = g.acc; }
    if (method === "GPS" && locId) args._location_id = locId;
    const { data, error } = await supabase.rpc("attendance_punch", args);
    setBusy(null);
    if (error) { toast.error(errMsg(error)); return; }
    toast.success(`${type.replace("_", " ").toLowerCase()} recorded at ${fmtTime((data as { occurred_at: string }).occurred_at, app.tz)} (server time)`);
    qc.invalidateQueries({ queryKey: ["att"] });
  }

  const canIn = !s?.check_in;
  const canOut = !!s?.check_in && !s?.check_out && !s?.on_break;
  const canBreak = !!s?.check_in && !s?.check_out && !s?.on_break;
  const canEndBreak = !!s?.on_break;

  return (
    <div>
      <PageHeader title="Check in / out" sub={`Official timestamps are generated by the server in ${app.tz}.`} />
      <div className="grid gap-6 lg:grid-cols-[1fr_360px]">
        <Panel title="Record attendance">
          <div className="space-y-5 p-5">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-2">
                <Label>Employee</Label>
                <Select value={empId} onValueChange={setEmpId}>
                  <SelectTrigger><SelectValue placeholder={selectable.length ? "Select employee" : "No employee linked to your account"} /></SelectTrigger>
                  <SelectContent>
                    {selectable.map((e) => <SelectItem key={e.id} value={e.id}>{e.full_name} · {e.employee_code}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Method</Label>
                <div className="grid grid-cols-2 gap-2">
                  {([["WEB", Globe, "Web"], ["GPS", MapPin, "GPS"]] as const).map(([m, Icon, l]) => (
                    <button key={m} type="button" onClick={() => { setMethod(m); if (m === "GPS" && gps === null) getGps(); }}
                      className={`flex items-center justify-center gap-2 rounded-md border px-3 py-2 text-sm ${method === m ? "border-primary bg-primary/10 text-primary" : "hover:bg-accent"}`}>
                      <Icon className="h-4 w-4" /> {l}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {method === "GPS" && (
              <div className="grid gap-4 rounded-md border bg-muted/20 p-4 sm:grid-cols-2">
                <div className="text-sm">
                  <div className="text-xs uppercase tracking-wider text-muted-foreground">Device location</div>
                  {busy === "gps" ? <div className="mt-1 flex items-center gap-2"><Loader2 className="h-3 w-3 animate-spin" /> Requesting…</div>
                    : gps === "unavailable" || gps === null ? <div className="mt-1 font-mono font-semibold text-destructive">LOCATION NOT AVAILABLE</div>
                    : <div className="mt-1 font-mono text-xs">{gps.lat.toFixed(5)}, {gps.lng.toFixed(5)} · ±{Math.round(gps.acc)}m</div>}
                  <button onClick={getGps} className="mt-2 text-xs text-primary underline">Refresh location</button>
                </div>
                <div className="space-y-2">
                  <Label className="text-xs">Validate against geofence</Label>
                  <Select value={locId} onValueChange={setLocId}>
                    <SelectTrigger><SelectValue placeholder="No geofence" /></SelectTrigger>
                    <SelectContent>
                      {(locs.data ?? []).map((l) => <SelectItem key={l.id} value={l.id}>{l.name} ({l.radius_m}m)</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            )}

            <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
              <Button size="lg" disabled={!emp || !canIn || !!busy} onClick={() => punch("CHECK_IN")}>
                {busy === "CHECK_IN" ? <Loader2 className="animate-spin" /> : <LogIn />} Check in
              </Button>
              <Button size="lg" variant="secondary" disabled={!emp || !canBreak || !!busy} onClick={() => punch("BREAK_START")}>
                <Coffee /> Start break
              </Button>
              <Button size="lg" variant="secondary" disabled={!emp || !canEndBreak || !!busy} onClick={() => punch("BREAK_END")}>
                <Play /> End break
              </Button>
              <Button size="lg" variant="outline" disabled={!emp || !canOut || !!busy} onClick={() => punch("CHECK_OUT")}>
                <LogOut /> Check out
              </Button>
            </div>

            <div className="grid gap-2 sm:grid-cols-3">
              {[["QR attendance", QrCode], ["Biometric", ScanFace], ["Attendance device", ScanFace]].map(([l, Icon]) => {
                const I = Icon as typeof QrCode;
                return (
                  <div key={l as string} className="flex items-center gap-2 rounded-md border border-dashed px-3 py-2 text-xs text-muted-foreground">
                    <I className="h-4 w-4" /> {l as string} <span className="ml-auto font-mono">NOT CONFIGURED</span>
                  </div>
                );
              })}
            </div>
          </div>
        </Panel>

        <Panel title="Today's state">
          {!emp ? <div className="p-5 text-sm text-muted-foreground">Select an employee to see today's attendance.</div> : (
            <div className="space-y-4 p-5">
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-display font-semibold">{emp.full_name}</div>
                  <div className="font-mono text-xs text-muted-foreground">{emp.employee_code}</div>
                </div>
                <StatusBadge status={s?.status ?? "NOT_MARKED"} />
              </div>
              <dl className="grid grid-cols-2 gap-3 text-sm">
                {[
                  ["Check-in", fmtTime(s?.check_in, app.tz)],
                  ["Check-out", fmtTime(s?.check_out, app.tz)],
                  ["Break taken", fmtMinutes(s?.break_minutes ?? 0)],
                  ["Current break", s?.on_break ? `since ${fmtTime(s.break_started_at, app.tz)}` : "—"],
                  ["Worked (net)", fmtMinutes(s?.net_minutes)],
                  ["Remaining", s?.net_minutes != null ? fmtMinutes(Math.max(0, s.expected_minutes - s.net_minutes)) : "—"],
                  ["Shift", s?.rule_start ? `${s.rule_start.slice(0, 5)}–${s.rule_end?.slice(0, 5)}` : "No rule"],
                  ["Overtime", fmtMinutes(s?.overtime_minutes ?? 0)],
                ].map(([k, v]) => (
                  <div key={k} className="rounded-md border bg-muted/20 p-2.5">
                    <dt className="text-[11px] uppercase tracking-wider text-muted-foreground">{k}</dt>
                    <dd className="mt-0.5 font-mono tabular">{v}</dd>
                  </div>
                ))}
              </dl>
            </div>
          )}
        </Panel>
      </div>

      {app.can.admin && <ManualEntry emps={selectable} />}
    </div>
  );
}

function ManualEntry({ emps }: { emps: { id: string; full_name: string; employee_code: string }[] }) {
  const qc = useQueryClient();
  const [f, setF] = useState({ emp: "", date: "", ci: "", co: "", reason: "" });
  const [busy, setBusy] = useState(false);
  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setBusy(true);
    const { error } = await supabase.rpc("manual_attendance", {
      _employee_id: f.emp, _work_date: f.date, _check_in: f.ci, _check_out: f.co || undefined as unknown as string, _reason: f.reason,
    });
    setBusy(false);
    if (error) { toast.error(errMsg(error)); return; }
    toast.success("Manual attendance recorded (marked MANUAL)");
    setF({ emp: "", date: "", ci: "", co: "", reason: "" });
    qc.invalidateQueries({ queryKey: ["att"] });
  }
  return (
    <Panel title={<span className="flex items-center gap-2"><PenLine className="h-4 w-4" /> Manual attendance (Super Admin)</span>} className="mt-6">
      <form onSubmit={submit} className="grid gap-3 p-5 md:grid-cols-6">
        <div className="space-y-1.5 md:col-span-2">
          <Label>Employee</Label>
          <Select value={f.emp} onValueChange={(v) => setF({ ...f, emp: v })}>
            <SelectTrigger><SelectValue placeholder="Select" /></SelectTrigger>
            <SelectContent>{emps.map((e) => <SelectItem key={e.id} value={e.id}>{e.full_name} · {e.employee_code}</SelectItem>)}</SelectContent>
          </Select>
        </div>
        <div className="space-y-1.5"><Label>Date</Label><Input type="date" required value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /></div>
        <div className="space-y-1.5"><Label>Check-in</Label><Input type="time" required value={f.ci} onChange={(e) => setF({ ...f, ci: e.target.value })} /></div>
        <div className="space-y-1.5"><Label>Check-out (optional)</Label><Input type="time" value={f.co} onChange={(e) => setF({ ...f, co: e.target.value })} /></div>
        <div className="space-y-1.5 md:col-span-6"><Label>Reason (required)</Label><Textarea required minLength={5} value={f.reason} onChange={(e) => setF({ ...f, reason: e.target.value })} /></div>
        <div className="md:col-span-6"><Button type="submit" disabled={busy || !f.emp}>{busy && <Loader2 className="animate-spin" />} Record manual attendance</Button></div>
      </form>
    </Panel>
  );
}
